In [1]:
import pandas

In [2]:
df=pandas.read_csv("Credit Card Default II (balance).csv")

In [3]:
df

income        age          loan  default
0     66155.925100  59.017015   8106.532131        0
1     34415.153970  48.117153   6564.745018        0
2     57317.170060  63.108049   8020.953296        0
3     42709.534200  45.751972   6103.642260        0
4     66952.688850  18.584336   8770.099235        1
...            ...        ...           ...      ...
3423  60903.191726  21.933924  10367.081892        1
3424  62235.644695  25.033016   8083.900063        1
3425  25597.850590  26.350344   3810.110335        1
3426  48164.194974  23.141976   6529.652892        1
3427  33055.808635  26.289612   5351.851138        1

[3428 rows x 4 columns]

In [10]:
print(df.isnull().sum().sort_values())

#no null valaues in dataset, no need to remove

income     0
age        0
loan       0
default    0
dtype: int64


In [24]:
#check datatype
df.dtypes

income     float64
age        float64
loan       float64
default      int64
dtype: object

In [16]:
#remove outlier
import numpy as np
from scipy import stats
z = stats.zscore(df.astype(np.float)) #zscore conversion need float
z = np.abs(z) #convert all to positive because the parity is not important
f = (z < 3).all(axis=1) #3 is your choice, axis =1 means by columns, f is a flag
df = df[f]


C:\Users\user\AppData\Local\Temp/ipykernel_8228/1320517513.py:4: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  z = stats.zscore(df.astype(np.float)) #zscore conversion need float


In [17]:
df

income        age          loan  default
0     66155.925100  59.017015   8106.532131        0
1     34415.153970  48.117153   6564.745018        0
2     57317.170060  63.108049   8020.953296        0
3     42709.534200  45.751972   6103.642260        0
4     66952.688850  18.584336   8770.099235        1
...            ...        ...           ...      ...
3423  60903.191726  21.933924  10367.081892        1
3424  62235.644695  25.033016   8083.900063        1
3425  25597.850590  26.350344   3810.110335        1
3426  48164.194974  23.141976   6529.652892        1
3427  33055.808635  26.289612   5351.851138        1

[3425 rows x 4 columns]

In [21]:
#split into x and y variables
Y = df.iloc[:,3]
X = df.iloc[:, 0:3]

In [34]:
#logistic regression
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.3)
print(X_train, X_test, Y_train, Y_test )

from sklearn import linear_model
model = linear_model.LogisticRegression()
model.fit(X_train, Y_train)
pred = model.predict(X_train)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_train, pred)
print(cm)
accuracy = (cm[0,0]+cm[1,1])/sum(sum(cm))
print(accuracy)


pred = model.predict(X_test)
cm = confusion_matrix(Y_test, pred)
print(cm)
accuracy = (cm[0,0]+cm[1,1])/sum(sum(cm))
print(accuracy)


           income        age          loan
1789  36535.31539  29.874892    271.725188
829   40230.97571  58.794096    745.194749
910   57330.61941  44.445651   1058.039202
1936  48187.34788  55.533010   2003.411850
91    42095.42220  55.366188   1183.704568
...           ...        ...           ...
708   29163.01588  43.956171   1469.129704
1861  55313.83225  25.212565   9733.113189
1689  31920.41272  52.159060    217.187962
1625  52263.35550  34.296092  10161.946670
1470  59475.49718  36.737130   2628.262124

[2397 rows x 3 columns]             income        age          loan
2818  48358.326931  30.847529   7727.871347
2759  61603.033724  30.165424  10383.435840
2488  64791.974021  29.085557  11618.106207
1882  51286.656400  45.859827   1134.234384
149   65635.661530  51.167714  12701.603480
...            ...        ...           ...
3405  43830.252484  24.290157   7597.574619
357   58597.383250  53.288034   2588.490266
2481  44294.452223  19.952635   8721.788885
2801  34720.352541 

In [36]:
#decision tree

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.3)

from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(max_depth=3)
model.fit(X_train, Y_train)
pred = model.predict(X_train)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_train, pred)
print(cm)
accuracy = (cm[0,0] + cm[1,1])/sum(sum(cm))
print(accuracy)

pred = model.predict(X_test)
cm = confusion_matrix(Y_test, pred)
print(cm)
accuracy = (cm[0,0] + cm[1,1])/sum(sum(cm))
print(accuracy)


[[1063  137]
 [   0 1197]]
0.9428452231956612
[[452  59]
 [  1 516]]
0.9416342412451362


In [ ]:
#decision tree

#optimisation
for i in range(100):
    print(i)
    model = tree.DecisionTreeRegressor(min_samples_split = i+2)
    model.fit(X_train1, Y_train1)
    pred = model.predict(X_validate)
    rmse = metrics.mean_squared_error(Y_validate, pred) ** 0.5
    print(rmse)


In [37]:
#random forest

from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(max_depth=3)
model.fit(X_train, Y_train)
pred = model.predict(X_train)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_train, pred)
print(cm)
accuracy = (cm[0,0] + cm[1,1])/sum(sum(cm))
print(accuracy)

pred = model.predict(X_test)
cm = confusion_matrix(Y_test, pred)
print(cm)
accuracy = (cm[0,0] + cm[1,1])/sum(sum(cm))
print(accuracy)


[[1079  121]
 [   1 1196]]
0.9491030454735085
[[463  48]
 [  2 515]]
0.9513618677042801


In [38]:
#XGBoost

from sklearn.ensemble import GradientBoostingClassifier
model = GradientBoostingClassifier(max_depth=3)
model.fit(X_train, Y_train)
pred = model.predict(X_train)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_train, pred)
print(cm)
accuracy = (cm[0,0] + cm[1,1])/sum(sum(cm))
print(accuracy)

pred = model.predict(X_test)
cm = confusion_matrix(Y_test, pred)
print(cm)
accuracy = (cm[0,0] + cm[1,1])/sum(sum(cm))
print(accuracy)


[[1199    1]
 [   0 1197]]
0.9995828118481435
[[504   7]
 [  2 515]]
0.9912451361867705


In [46]:
#Neural network MLP

from sklearn.neural_network import MLPClassifier
model=MLPClassifier(solver="lbfgs",hidden_layer_sizes=(7,8))
model.fit(X,Y)
pred=model.predict(X)
print(pred)

#confusion matrix

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y,pred)
print(cm)


[0 1 1 ... 1 1 1]
[[1299  412]
 [ 162 1552]]


C:\Users\user\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:500: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


In [47]:
#dump model

import joblib
joblib.dump(model,"Creditcard")

['Creditcard']